### ISSUE TITLE
Task 2.3

### ISSUE THREAD

**Issue by Tommy4chan** [MUGnifisent/KL_KurGen#5]
When changing value F0 = generate_f(pn)[0] to F0 = generate_f(pn)[1] or other index

![image](https://user-images.githubusercontent.com/47715567/197179945-552fc01a-04bb-4e4b-b97e-fbd11b582099.png)

Such thing is unreal

**Comment by MUGnifisent** [comment]
Issue was fixed, pull the code and try again.
